language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install flake8

# command to install dependencies
install:
  - "pip install ."

# command to run tests
script:
  - flake8 --version
  - flake8 --ignore E501 numpy_buffer samples test
  - nosetests
